services:
  app:
    build: .
    container_name: work-progress-app
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
